"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowRight, CheckCircle2, Circle, Download, FileSearch, FileText, Layers3, Loader2, MessageSquare, Network, Printer, ShieldCheck, X } from "lucide-react";
import type { AnalysisResult, DocumentChunk, Finding, FunctionMatch, SourceReference, UnitMapping } from "@/lib/types";
import DocumentStructure from "./DocumentStructure";
import { OrgChart } from "./OrgChart";

type Snapshot = { id: string; status: string; stage: string; error?: string; result: AnalysisResult | null; documents: { id: string; filename: string; side: string; type: string; size: number; chunks: DocumentChunk[] }[] };
const stages = ["Чтение и проверка документов", "Извлечение структуры и функций", "Сопоставление подразделений и функций", "Проверка потерь, пересечений и конфликтов", "Формирование аналитического заключения", "Готово"];
const statusLabels: Record<string, string> = { preserved: "Сохранена", modified: "Изменена", moved: "Перемещена", possibly_lost: "Возможная потеря", new: "Новая" };
const mappingLabels: Record<string, string> = { unchanged: "Сохранено", renamed: "Переименовано", transformed: "Преобразовано", split: "Разделено", merged: "Объединено", removed: "Не найдено после", created: "Создано" };
const findingLabels: Record<string, string> = { lost_function: "Потенциальная потеря", duplicated_function: "Пересечение функций", moved_function: "Перемещение", modified_function: "Изменение", conflict_of_interest: "Конфликт интересов", structural_change: "Изменение структуры", new_function: "Новая функция" };
function percent(value: number) { return `${Math.round(value * 100)}%`; }
function download(name: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function markdown(result: AnalysisResult): string { return `# Аналитическое заключение\n\n${result.report.executiveSummary}\n\n## Изменения структуры\n${result.report.structuralChangesSummary}\n\n## Риски\n${result.report.keyRisks.map((x) => `- ${x}`).join("\n")}\n\n## Выводы и источники\n${result.findings.map((f) => `### ${f.title}\n${f.summary}\n${f.reasoning}\nУверенность: ${percent(f.confidence)}\n${[...f.beforeRefs, ...f.afterRefs].map((r) => `- ${r.filename}, ${r.section ? `раздел ${r.section}` : r.page ? `стр. ${r.page}` : r.sheet ? `${r.sheet}, строка ${r.row}` : `абзац ${r.paragraph}`}: «${r.quote}»`).join("\n")}`).join("\n\n")}\n\n## Рекомендации\n${result.report.recommendations.map((x) => `- ${x}`).join("\n")}\n\n${result.report.conclusion}\n\nВыводы носят рекомендательный характер и требуют проверки ответственным сотрудником.\n`; }
export default function AnalysisView({ id }: { id: string }) {
  const router = useRouter(); const search = useSearchParams(); const started = useRef(false);
  const [data, setData] = useState<Snapshot>(); const [error, setError] = useState(""); const [tab, setTab] = useState("overview"); const [filter, setFilter] = useState("all"); const [source, setSource] = useState<SourceReference | null>(null);
  const [chatInput, setChatInput] = useState(""); const [chatMessages, setChatMessages] = useState<{q:string;a:string}[]>([]); const [chatLoading, setChatLoading] = useState(false);
  const [showNeedsReview, setShowNeedsReview] = useState(false);
  const refresh = useCallback(async () => { try { const response = await fetch(`/api/analyses/${id}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось загрузить анализ."); } }, [id]);
  useEffect(() => { const first = !data?.status && setTimeout(() => void refresh(), 0); const timer = data?.status === "complete" || data?.status === "failed" ? undefined : setInterval(() => void refresh(), 2500); return () => { if (first) clearTimeout(first); if (timer) clearInterval(timer); }; }, [refresh, data?.status]);
  useEffect(() => { if (search.get("run") !== "1" || started.current) return; started.current = true; fetch(`/api/analyses/${id}/run`, { method: "POST" }).then(async (response) => { const payload = await response.json(); if (!response.ok || payload.status === "failed") setError(payload.error || "Ошибка анализа."); void refresh(); router.replace(`/analysis/${id}`); }).catch(() => setError("Не удалось запустить анализ.")); }, [id, refresh, router, search]);
  const result = data?.result; const units = result?.units ?? [];
  const subdivisionMappings = result?.unitMappings.filter((mapping) => ![...mapping.beforeUnitIds, ...mapping.afterUnitIds].some((unitId) => units.find((unit) => unit.id === unitId)?.isRoot)) ?? [];
  const unitName = (unitId: string) => units.find((unit) => unit.id === unitId)?.name ?? "—";
  const refs = (items: SourceReference[]) => <div className="reference-list">{items.map((ref, i) => <button className="source-link" key={`${ref.chunkId}-${i}`} onClick={() => setSource(ref)}><FileSearch size={15}/>{ref.filename} · {ref.section ? `п. ${ref.section}` : ref.page ? `стр. ${ref.page}` : ref.sheet ? `${ref.sheet}, строка ${ref.row}` : `абз. ${ref.paragraph}`}</button>)}</div>;
  const filteredMatches = useMemo(() => (result?.functionMatches ?? []).filter((match) => filter === "all" || match.status === filter), [result, filter]);
  const selectedDocument = source && data?.documents.find((document) => document.id === source.documentId);
  const selectedIndex = source && selectedDocument ? selectedDocument.chunks.findIndex((chunk) => chunk.id === source.chunkId) : -1;
  const selectedChunk = selectedIndex >= 0 ? selectedDocument?.chunks[selectedIndex] : undefined;
  const contextBefore = selectedIndex > 0 ? selectedDocument?.chunks[selectedIndex - 1] : undefined;
  const contextAfter = selectedIndex >= 0 ? selectedDocument?.chunks[selectedIndex + 1] : undefined;
  async function askChat() {
    if (!chatInput.trim() || chatLoading) return;
    const q = chatInput.trim(); setChatInput(""); setChatLoading(true);
    try {
      const response = await fetch(`/api/analyses/${id}/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: q }) });
      const payload = await response.json();
      setChatMessages((m) => [...m, { q, a: payload.answer || payload.error || "Нет ответа." }]);
    } catch { setChatMessages((m) => [...m, { q, a: "Ошибка запроса." }]); }
    setChatLoading(false);
  }
  return <main className="site-shell results-shell"><header className="topbar"><button className="back-link" onClick={() => router.push("/")}><ArrowLeft size={17}/> Новый анализ</button><div className="brand"><span className="brand-icon"><Layers3 size={20}/></span><span>VIVALET <small>AI Organization Auditor</small></span></div><span className="top-note"><ShieldCheck size={16}/> Источники проверены</span></header>
    <div className="result-heading"><div><span className="step">АНАЛИТИЧЕСКОЕ ДЕЛО / {id.slice(0, 8).toUpperCase()}</span><h1>Анализ организационных изменений</h1><p>Сопоставление структуры, функций и зон ответственности</p></div>{result && <div className="export-group"><button onClick={() => download(`analysis-${id}.json`, JSON.stringify(result, null, 2), "application/json")}><Download size={16}/> JSON</button><button onClick={() => download(`analysis-${id}.md`, markdown(result), "text/markdown")}><Download size={16}/> Markdown</button><button onClick={() => window.print()} title="Печать"><Printer size={16}/> Печать</button></div>}</div>
    {error && <div className="alert">{error}</div>}{data?.error && <div className="alert">{data.error}</div>}
    {(!result) && <section className="progress-panel"><div className="progress-head"><div className="pulse-icon"><Loader2 size={23} className={data?.status === "running" ? "spin" : ""}/></div><div><h2>{data?.status === "failed" ? "Анализ остановлен" : data?.status === "running" ? "Идёт анализ документов" : "Подготовка анализа"}</h2><p>{data?.stage || "Загружаем состояние..."}</p></div></div><div className="progress-list">{stages.map((stage, index) => { const current = stages.findIndex((entry) => data?.stage?.startsWith(entry)); const done = current > index || data?.status === "complete"; return <div key={stage} className={done ? "progress-item done" : current === index ? "progress-item active" : "progress-item"}>{done ? <CheckCircle2 size={19}/> : current === index ? <Loader2 size={19} className="spin"/> : <Circle size={19}/>}<span>{stage}</span></div>; })}</div>{data?.status === "failed" && <button className="primary-button" onClick={() => { setError(""); setData((current) => current ? { ...current, status: "running", stage: "Чтение и проверка документов", error: undefined } : current); void fetch(`/api/analyses/${id}/run`, { method: "POST" }).then(() => refresh()).catch(() => setError("Не удалось повторить анализ.")); }}>Повторить анализ <ArrowRight size={17}/></button>}</section>}
    {result && <><div className="mode-note"><ShieldCheck size={17}/>{result.mode === "ai" ? "AI анализ: структурированное извлечение, семантический поиск и проверка сопоставлений." : "Режим правил: OPENAI_API_KEY не задан. Результат получен эвристиками и требует более тщательной проверки."}</div><nav className="tabs">{[["overview", "Обзор"], ["structure", "Структура"], ["graph", "Граф"], ["functions", "Функции"], ["findings", `Выводы · ${result.findings.length}`], ["report", "Заключение"], ...(result.mode === "ai" ? [["chat", "Ассистент"]] : [])].map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{key === "graph" ? <><Network size={14} style={{display:"inline",marginRight:4}}/>{label}</> : key === "chat" ? <><MessageSquare size={14} style={{display:"inline",marginRight:4}}/>{label}</> : label}</button>)}</nav>
      {tab === "overview" && <><div className="metrics">{[["Оргподразделений до", units.filter((u) => u.side === "before" && !u.isRoot).length], ["Оргподразделений после", units.filter((u) => u.side === "after" && !u.isRoot).length], ["Возможных потерь", result.findings.filter((f) => f.type === "lost_function").length], ["Пересечений", result.findings.filter((f) => f.type === "duplicated_function").length], ["Конфликтов", result.findings.filter((f) => f.type === "conflict_of_interest").length]].map(([label, value]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><DocumentStructure documents={data?.documents ?? []}/><div className="overview-grid"><section className="panel"><div className="panel-title"><h2>Краткое заключение</h2><FileText size={19}/></div><p className="lead-text">{result.report.executiveSummary}</p><p>{result.report.structuralChangesSummary}</p><button className="text-button" onClick={() => setTab("report")}>Открыть заключение <ArrowRight size={16}/></button></section><section className="panel"><div className="panel-title"><h2>На что обратить внимание</h2><ShieldCheck size={19}/></div><ul className="risk-list">{result.report.keyRisks.map((risk, i) => <li key={i}>{risk}</li>)}</ul><button className="text-button" onClick={() => setTab("findings")}>Смотреть выводы <ArrowRight size={16}/></button></section></div><section className="panel"><div className="panel-title"><h2>Загруженные документы</h2></div><div className="document-strip">{data?.documents.map((doc) => <div className="document-pill" key={doc.id}><FileText size={18}/><div><strong>{doc.filename}</strong><small>{doc.side === "before" ? "До" : "После"} · {doc.type.toUpperCase()} · {doc.chunks.length} фрагментов</small></div></div>)}</div></section></>}
      {tab === "structure" && <section className="panel"><div className="panel-title"><div><span className="step">СОПОСТАВЛЕНИЕ ПОДРАЗДЕЛЕНИЙ</span><h2>Структурные изменения</h2></div></div><div className="mapping-table"><div className="table-head"><span>ДО</span><span>ИЗМЕНЕНИЕ</span><span>ПОСЛЕ</span></div>{subdivisionMappings.map((mapping: UnitMapping, index) => <div className="mapping-row" key={index}><div><strong>{mapping.beforeUnitIds.map(unitName).join(", ") || "—"}</strong></div><div><span className={`badge ${mapping.transformation}`}>{mappingLabels[mapping.transformation]}</span><small>{percent(mapping.confidence)}</small></div><div><strong>{mapping.afterUnitIds.map(unitName).join(", ") || "—"}</strong><p>{mapping.explanation}</p>{refs(mapping.sourceRefs)}</div></div>)}</div></section>}
      {tab === "functions" && <section className="panel"><div className="panel-title"><div><span className="step">ФУНКЦИОНАЛЬНАЯ МАТРИЦА</span><h2>Сопоставление функций</h2></div><span className="count-pill">{filteredMatches.length} записей</span></div><div className="filters">{[["all", "Все"], ["preserved", "Сохранены"], ["modified", "Изменены"], ["moved", "Перемещены"], ["possibly_lost", "Возможные потери"], ["new", "Новые"]].map(([key, label]) => <button key={key} className={filter === key ? "active" : ""} onClick={() => setFilter(key)}>{label}</button>)}</div><div className="function-list">{filteredMatches.map((match: FunctionMatch, index) => <div className="function-row" key={index}><div><small>ДО · {match.beforeUnit || "—"}</small><p>{match.beforeText || "—"}</p>{refs(match.beforeRefs)}</div><ArrowRight className="row-arrow" size={18}/><div><small>ПОСЛЕ · {match.afterUnit || "—"}</small><p>{match.afterText || "Явного соответствия не найдено"}</p>{refs(match.afterRefs)}</div><div className="match-status"><span className={`badge ${match.status}`}>{statusLabels[match.status]}</span><strong>{percent(match.confidence)}</strong></div></div>)}</div></section>}
      {tab === "graph" && <section className="panel"><div className="panel-title"><div><span className="step">ОРГАНИЗАЦИОННАЯ СТРУКТУРА</span><h2>Граф изменений</h2></div></div><OrgChart unitMappings={subdivisionMappings} beforeUnits={units.filter(u=>u.side==="before"&&!u.isRoot)} afterUnits={units.filter(u=>u.side==="after"&&!u.isRoot)}/></section>}
      {tab === "findings" && <section className="findings-layout"><div className="section-heading compact"><div><span className="step">ПРОВЕРЯЕМЫЕ ВЫВОДЫ</span><h2>Риски и изменения</h2><p>Выводы ниже прошли проверку наличия исходных фрагментов.</p></div><span className="count-pill">{result.findings.length} выводов</span></div>{!result.findings.length && <div className="panel empty">По выбранным документам значимых выводов с достаточными источниками не сформировано.</div>}{result.findings.map((item: Finding) => { const isDualFn = item.type === "duplicated_function" || item.type === "conflict_of_interest"; return <article className="finding-card" key={item.id}><div className="finding-head"><span className={`severity ${item.severity}`}>{item.severity === "high" ? "ВЫСОКИЙ ПРИОРИТЕТ" : item.severity === "medium" ? "СРЕДНИЙ ПРИОРИТЕТ" : "ИНФОРМАЦИЯ"}</span><span className="confidence">Уверенность {percent(item.confidence)}</span></div><h3>{item.title}</h3><span className="finding-type">{findingLabels[item.type]}</span><p className="finding-summary">{item.summary}</p><div className="reason-box"><strong>Почему система так считает</strong><p>{item.reasoning}</p></div><div className="evidence-grid"><div><small>{isDualFn ? "ФУНКЦИЯ А" : "ДО"}</small>{item.beforeRefs.length ? refs(item.beforeRefs) : <p>—</p>}</div><div><small>{isDualFn ? "ФУНКЦИЯ Б" : "ПОСЛЕ"}</small>{item.afterRefs.length ? refs(item.afterRefs) : <p>Явного соответствия не найдено</p>}</div></div>{item.recommendation && <p className="recommendation">Рекомендация: {item.recommendation}</p>}</article>; })}
        {result.needsReview?.length > 0 && <div className="needs-review-section"><button className="needs-review-toggle" onClick={() => setShowNeedsReview((v) => !v)}><span>Требуют проверки · {result.needsReview.length} вывода{result.needsReview.length !== 1 ? "а" : ""}</span><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{transform:showNeedsReview?"rotate(180deg)":"none",transition:"transform .2s"}}><path d="M19 9l-7 7-7-7"/></svg></button>{showNeedsReview && <div className="needs-review-list">{result.needsReview.map((item: Finding) => <div className="needs-review-item" key={item.id}><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:4}}><span className="badge">{findingLabels[item.type]}</span><span style={{fontSize:11,color:"#9aacbc"}}>Недостаточно доказательств</span></div><p style={{margin:"4px 0",fontSize:13,color:"#4b6179"}}>{item.summary.slice(0,200)}</p></div>)}</div>}</div>}
      </section>}
      {tab === "report" && <section className="report-panel panel"><span className="step">ИТОГОВЫЙ ДОКУМЕНТ</span><h2>Аналитическое заключение</h2><div className="report-section"><h3>Краткое резюме</h3><p>{result.report.executiveSummary}</p></div><div className="report-section"><h3>Изменения организационной структуры</h3><p>{result.report.structuralChangesSummary}</p><button className="text-button" onClick={() => setTab("structure")}>Открыть сопоставления <ArrowRight size={16}/></button></div><div className="report-section"><h3>Ключевые риски</h3><ul>{result.report.keyRisks.map((risk, i) => <li key={i}>{risk}</li>)}</ul><button className="text-button" onClick={() => setTab("findings")}>Открыть выводы с источниками <ArrowRight size={16}/></button></div><div className="report-section"><h3>Рекомендации</h3><ol>{result.report.recommendations.map((recommendation, i) => <li key={i}>{recommendation}</li>)}</ol></div><div className="report-section"><h3>Заключение</h3><p>{result.report.conclusion}</p></div><div className="disclaimer">Выводы сформированы ИИ или правилами и носят рекомендательный характер. Окончательная оценка должна выполняться ответственным сотрудником.</div></section>}
      {tab === "chat" && <section className="panel chat-panel"><div className="panel-title"><div><span className="step">АССИСТЕНТ</span><h2>Вопросы по анализу</h2></div><MessageSquare size={19}/></div><p style={{color:"#687d92",marginBottom:20}}>Задайте вопрос по сопоставлению подразделений, выявленным рискам и изменениям функций.</p><div className="chat-messages">{chatMessages.length === 0 && <div className="chat-placeholder">Например: «Какие функции были перемещены?» или «В каких подразделениях выявлен конфликт интересов?»</div>}{chatMessages.map((msg, i) => <div key={i} className="chat-message-group"><div className="chat-bubble user-bubble"><strong>Вопрос:</strong> {msg.q}</div><div className="chat-bubble assistant-bubble"><strong>Ответ:</strong> {msg.a}</div></div>)}{chatLoading && <div className="chat-loading"><Loader2 size={18} className="spin"/><span>Ассистент готовит ответ...</span></div>}</div><div className="chat-input-row"><input type="text" placeholder="Задайте вопрос по результатам анализа..." value={chatInput} onChange={(e) => setChatInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) void askChat(); }} disabled={chatLoading} className="chat-input"/><button className="primary-button" onClick={() => void askChat()} disabled={chatLoading || !chatInput.trim()}>Отправить</button></div></section>}
    </>}
    {source && <div className="drawer-backdrop" onClick={() => setSource(null)}><aside className="source-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><span className="step">ПЕРВОИСТОЧНИК</span><h2>Фрагмент документа</h2></div><button onClick={() => setSource(null)} aria-label="Закрыть"><X size={20}/></button></div><div className="source-meta"><FileText size={20}/><div><strong>{source.filename}</strong><span>{source.section ? `Раздел ${source.section}` : source.page ? `Страница ${source.page}` : source.sheet ? `Лист ${source.sheet}, строка ${source.row}` : `Абзац ${source.paragraph}`}</span></div></div>{contextBefore && <p className="source-neighbor">{contextBefore.text}</p>}<div className="source-content">{selectedChunk?.text.includes(source.quote) ? <>{selectedChunk.text.split(source.quote)[0]}<mark>{source.quote}</mark>{selectedChunk.text.slice(selectedChunk.text.indexOf(source.quote) + source.quote.length)}</> : source.quote}</div>{contextAfter && <p className="source-neighbor">{contextAfter.text}</p>}<p className="source-caption">Цитата сверена с извлечённым текстом исходного документа.</p></aside></div>}
  </main>;
}



